### ISSUE TITLE
“No module named 'wsovod'“”

### ISSUE THREAD

**Issue by Yinyf0804** [HunterJ-Lin/WSOVOD#8]
Thanks for the great work, but when I run the code, it shows the following error:

`File "/usr/local/lib/python3.9/dist-packages/torchvision/models/detection/anchor_utils.py", line 63, in AnchorGenerator
    device: torch.device = torch.device("cpu"),
/usr/local/lib/python3.9/dist-packages/torchvision/models/detection/anchor_utils.py:63: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:68.)
  device: torch.device = torch.device("cpu"),
Traceback (most recent call last):
  File "/ghome/yinyf/WSOVOD-master/tools/train_net.py", line 28, in <module>
    from wsovod.config import add_wsovod_config
ModuleNotFoundError: No module named 'wsovod'`

What can i do to deal with it?

**Comment by HunterJ-Lin** [comment]
you should install wsovod first. “you should cd to WSOVOD dir, and pip install -e .”

**Comment by machao670** [comment]
Thanks for the great work, i encountered the same problem and i have run pip install -e .  however the problem is still exist
